//
// Licensed to the Apache Software Foundation (ASF) under one or more contributor license
// agreements. See the NOTICE file distributed with this work for additional information regarding
// copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance with the License. You may obtain a
// copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
// or implied. See the License for the specific language governing permissions and limitations under
// the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: v1/function_API.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ExecuteFunctionOnRegionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionID string          `protobuf:"bytes,1,opt,name=functionID,proto3" json:"functionID,omitempty"`
	Region     string          `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Arguments  *EncodedValue   `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	KeyFilter  []*EncodedValue `protobuf:"bytes,4,rep,name=keyFilter,proto3" json:"keyFilter,omitempty"`
}

func (x *ExecuteFunctionOnRegionRequest) Reset() {
	*x = ExecuteFunctionOnRegionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_function_API_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteFunctionOnRegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFunctionOnRegionRequest) ProtoMessage() {}

func (x *ExecuteFunctionOnRegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_function_API_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFunctionOnRegionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteFunctionOnRegionRequest) Descriptor() ([]byte, []int) {
	return file_v1_function_API_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteFunctionOnRegionRequest) GetFunctionID() string {
	if x != nil {
		return x.FunctionID
	}
	return ""
}

func (x *ExecuteFunctionOnRegionRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ExecuteFunctionOnRegionRequest) GetArguments() *EncodedValue {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ExecuteFunctionOnRegionRequest) GetKeyFilter() []*EncodedValue {
	if x != nil {
		return x.KeyFilter
	}
	return nil
}

type ExecuteFunctionOnRegionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*EncodedValue `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // some functions don't return results.
}

func (x *ExecuteFunctionOnRegionResponse) Reset() {
	*x = ExecuteFunctionOnRegionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_function_API_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteFunctionOnRegionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFunctionOnRegionResponse) ProtoMessage() {}

func (x *ExecuteFunctionOnRegionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_function_API_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFunctionOnRegionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteFunctionOnRegionResponse) Descriptor() ([]byte, []int) {
	return file_v1_function_API_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteFunctionOnRegionResponse) GetResults() []*EncodedValue {
	if x != nil {
		return x.Results
	}
	return nil
}

type ExecuteFunctionOnMemberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionID string        `protobuf:"bytes,1,opt,name=functionID,proto3" json:"functionID,omitempty"`
	MemberName []string      `protobuf:"bytes,2,rep,name=memberName,proto3" json:"memberName,omitempty"`
	Arguments  *EncodedValue `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *ExecuteFunctionOnMemberRequest) Reset() {
	*x = ExecuteFunctionOnMemberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_function_API_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteFunctionOnMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFunctionOnMemberRequest) ProtoMessage() {}

func (x *ExecuteFunctionOnMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_function_API_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFunctionOnMemberRequest.ProtoReflect.Descriptor instead.
func (*ExecuteFunctionOnMemberRequest) Descriptor() ([]byte, []int) {
	return file_v1_function_API_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteFunctionOnMemberRequest) GetFunctionID() string {
	if x != nil {
		return x.FunctionID
	}
	return ""
}

func (x *ExecuteFunctionOnMemberRequest) GetMemberName() []string {
	if x != nil {
		return x.MemberName
	}
	return nil
}

func (x *ExecuteFunctionOnMemberRequest) GetArguments() *EncodedValue {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type ExecuteFunctionOnMemberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*EncodedValue `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // some functions don't return results.
}

func (x *ExecuteFunctionOnMemberResponse) Reset() {
	*x = ExecuteFunctionOnMemberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_function_API_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteFunctionOnMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFunctionOnMemberResponse) ProtoMessage() {}

func (x *ExecuteFunctionOnMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_function_API_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFunctionOnMemberResponse.ProtoReflect.Descriptor instead.
func (*ExecuteFunctionOnMemberResponse) Descriptor() ([]byte, []int) {
	return file_v1_function_API_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteFunctionOnMemberResponse) GetResults() []*EncodedValue {
	if x != nil {
		return x.Results
	}
	return nil
}

type ExecuteFunctionOnGroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionID string        `protobuf:"bytes,1,opt,name=functionID,proto3" json:"functionID,omitempty"`
	GroupName  []string      `protobuf:"bytes,2,rep,name=groupName,proto3" json:"groupName,omitempty"`
	Arguments  *EncodedValue `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
}

func (x *ExecuteFunctionOnGroupRequest) Reset() {
	*x = ExecuteFunctionOnGroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_function_API_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteFunctionOnGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFunctionOnGroupRequest) ProtoMessage() {}

func (x *ExecuteFunctionOnGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_function_API_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFunctionOnGroupRequest.ProtoReflect.Descriptor instead.
func (*ExecuteFunctionOnGroupRequest) Descriptor() ([]byte, []int) {
	return file_v1_function_API_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteFunctionOnGroupRequest) GetFunctionID() string {
	if x != nil {
		return x.FunctionID
	}
	return ""
}

func (x *ExecuteFunctionOnGroupRequest) GetGroupName() []string {
	if x != nil {
		return x.GroupName
	}
	return nil
}

func (x *ExecuteFunctionOnGroupRequest) GetArguments() *EncodedValue {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type ExecuteFunctionOnGroupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*EncodedValue `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // some functions don't return results.
}

func (x *ExecuteFunctionOnGroupResponse) Reset() {
	*x = ExecuteFunctionOnGroupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_function_API_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteFunctionOnGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteFunctionOnGroupResponse) ProtoMessage() {}

func (x *ExecuteFunctionOnGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_function_API_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteFunctionOnGroupResponse.ProtoReflect.Descriptor instead.
func (*ExecuteFunctionOnGroupResponse) Descriptor() ([]byte, []int) {
	return file_v1_function_API_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteFunctionOnGroupResponse) GetResults() []*EncodedValue {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_v1_function_API_proto protoreflect.FileDescriptor

var file_v1_function_API_proto_rawDesc = []byte{
	0x0a, 0x15, 0x76, 0x31, 0x2f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x41, 0x50,
	0x49, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x76, 0x31, 0x1a, 0x13, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x02, 0x0a,
	0x1e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x4f, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x5a, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x6f,
	0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x5a, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22,
	0x79, 0x0a, 0x1f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x4f, 0x6e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x56, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65,
	0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x1e, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x6e,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x1e, 0x0a,
	0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0a, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x5a, 0x0a,
	0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x3c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x67, 0x65,
	0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09,
	0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x79, 0x0a, 0x1f, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x6e, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e,
	0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x22, 0xb9, 0x01, 0x0a, 0x1d, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x5a, 0x0a, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70,
	0x61, 0x63, 0x68, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x09, 0x61, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0x78, 0x0a, 0x1e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x4f, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x56, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65,
	0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x42, 0x30, 0x5a, 0x2e, 0x6f, 0x72,
	0x67, 0x2f, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_function_API_proto_rawDescOnce sync.Once
	file_v1_function_API_proto_rawDescData = file_v1_function_API_proto_rawDesc
)

func file_v1_function_API_proto_rawDescGZIP() []byte {
	file_v1_function_API_proto_rawDescOnce.Do(func() {
		file_v1_function_API_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_function_API_proto_rawDescData)
	})
	return file_v1_function_API_proto_rawDescData
}

var file_v1_function_API_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_function_API_proto_goTypes = []interface{}{
	(*ExecuteFunctionOnRegionRequest)(nil),  // 0: org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnRegionRequest
	(*ExecuteFunctionOnRegionResponse)(nil), // 1: org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnRegionResponse
	(*ExecuteFunctionOnMemberRequest)(nil),  // 2: org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnMemberRequest
	(*ExecuteFunctionOnMemberResponse)(nil), // 3: org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnMemberResponse
	(*ExecuteFunctionOnGroupRequest)(nil),   // 4: org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnGroupRequest
	(*ExecuteFunctionOnGroupResponse)(nil),  // 5: org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnGroupResponse
	(*EncodedValue)(nil),                    // 6: org.apache.geode.internal.protocol.protobuf.v1.EncodedValue
}
var file_v1_function_API_proto_depIdxs = []int32{
	6, // 0: org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnRegionRequest.arguments:type_name -> org.apache.geode.internal.protocol.protobuf.v1.EncodedValue
	6, // 1: org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnRegionRequest.keyFilter:type_name -> org.apache.geode.internal.protocol.protobuf.v1.EncodedValue
	6, // 2: org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnRegionResponse.results:type_name -> org.apache.geode.internal.protocol.protobuf.v1.EncodedValue
	6, // 3: org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnMemberRequest.arguments:type_name -> org.apache.geode.internal.protocol.protobuf.v1.EncodedValue
	6, // 4: org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnMemberResponse.results:type_name -> org.apache.geode.internal.protocol.protobuf.v1.EncodedValue
	6, // 5: org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnGroupRequest.arguments:type_name -> org.apache.geode.internal.protocol.protobuf.v1.EncodedValue
	6, // 6: org.apache.geode.internal.protocol.protobuf.v1.ExecuteFunctionOnGroupResponse.results:type_name -> org.apache.geode.internal.protocol.protobuf.v1.EncodedValue
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_v1_function_API_proto_init() }
func file_v1_function_API_proto_init() {
	if File_v1_function_API_proto != nil {
		return
	}
	file_v1_basicTypes_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_function_API_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteFunctionOnRegionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_function_API_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteFunctionOnRegionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_function_API_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteFunctionOnMemberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_function_API_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteFunctionOnMemberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_function_API_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteFunctionOnGroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_function_API_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteFunctionOnGroupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_function_API_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_function_API_proto_goTypes,
		DependencyIndexes: file_v1_function_API_proto_depIdxs,
		MessageInfos:      file_v1_function_API_proto_msgTypes,
	}.Build()
	File_v1_function_API_proto = out.File
	file_v1_function_API_proto_rawDesc = nil
	file_v1_function_API_proto_goTypes = nil
	file_v1_function_API_proto_depIdxs = nil
}
