//
// Licensed to the Apache Software Foundation (ASF) under one or more contributor license
// agreements. See the NOTICE file distributed with this work for additional information regarding
// copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance with the License. You may obtain a
// copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
// or implied. See the License for the specific language governing permissions and limitations under
// the License.

//
// These ProtoBuf files are part of an experimental interface.
// Use this interface at your own risk.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: v1/basicTypes.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ErrorCode int32

const (
	ErrorCode_INVALID_ERROR_CODE           ErrorCode = 0
	ErrorCode_AUTHENTICATION_REQUIRED      ErrorCode = 10
	ErrorCode_AUTHENTICATION_FAILED        ErrorCode = 11
	ErrorCode_ALREADY_AUTHENTICATED        ErrorCode = 12
	ErrorCode_AUTHENTICATION_NOT_SUPPORTED ErrorCode = 13
	ErrorCode_AUTHORIZATION_FAILED         ErrorCode = 20
	ErrorCode_INVALID_REQUEST              ErrorCode = 50
	ErrorCode_UNSUPPORTED_OPERATION        ErrorCode = 60
	ErrorCode_SERVER_ERROR                 ErrorCode = 100
	ErrorCode_NO_AVAILABLE_SERVER          ErrorCode = 101
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "INVALID_ERROR_CODE",
		10:  "AUTHENTICATION_REQUIRED",
		11:  "AUTHENTICATION_FAILED",
		12:  "ALREADY_AUTHENTICATED",
		13:  "AUTHENTICATION_NOT_SUPPORTED",
		20:  "AUTHORIZATION_FAILED",
		50:  "INVALID_REQUEST",
		60:  "UNSUPPORTED_OPERATION",
		100: "SERVER_ERROR",
		101: "NO_AVAILABLE_SERVER",
	}
	ErrorCode_value = map[string]int32{
		"INVALID_ERROR_CODE":           0,
		"AUTHENTICATION_REQUIRED":      10,
		"AUTHENTICATION_FAILED":        11,
		"ALREADY_AUTHENTICATED":        12,
		"AUTHENTICATION_NOT_SUPPORTED": 13,
		"AUTHORIZATION_FAILED":         20,
		"INVALID_REQUEST":              50,
		"UNSUPPORTED_OPERATION":        60,
		"SERVER_ERROR":                 100,
		"NO_AVAILABLE_SERVER":          101,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_basicTypes_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_v1_basicTypes_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_v1_basicTypes_proto_rawDescGZIP(), []int{0}
}

type Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *EncodedValue `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *EncodedValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Entry) Reset() {
	*x = Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_basicTypes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_basicTypes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_v1_basicTypes_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetKey() *EncodedValue {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Entry) GetValue() *EncodedValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type EncodedValueList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element []*EncodedValue `protobuf:"bytes,1,rep,name=element,proto3" json:"element,omitempty"`
}

func (x *EncodedValueList) Reset() {
	*x = EncodedValueList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_basicTypes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodedValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedValueList) ProtoMessage() {}

func (x *EncodedValueList) ProtoReflect() protoreflect.Message {
	mi := &file_v1_basicTypes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedValueList.ProtoReflect.Descriptor instead.
func (*EncodedValueList) Descriptor() ([]byte, []int) {
	return file_v1_basicTypes_proto_rawDescGZIP(), []int{1}
}

func (x *EncodedValueList) GetElement() []*EncodedValue {
	if x != nil {
		return x.Element
	}
	return nil
}

//Represents a table, such as the results of
//an OQL query. The field names and all rows
//should have the same number of elements.
type Table struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldName []string            `protobuf:"bytes,1,rep,name=fieldName,proto3" json:"fieldName,omitempty"`
	Row       []*EncodedValueList `protobuf:"bytes,2,rep,name=row,proto3" json:"row,omitempty"`
}

func (x *Table) Reset() {
	*x = Table{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_basicTypes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_v1_basicTypes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_v1_basicTypes_proto_rawDescGZIP(), []int{2}
}

func (x *Table) GetFieldName() []string {
	if x != nil {
		return x.FieldName
	}
	return nil
}

func (x *Table) GetRow() []*EncodedValueList {
	if x != nil {
		return x.Row
	}
	return nil
}

type EncodedValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*EncodedValue_IntResult
	//	*EncodedValue_LongResult
	//	*EncodedValue_ShortResult
	//	*EncodedValue_ByteResult
	//	*EncodedValue_BooleanResult
	//	*EncodedValue_DoubleResult
	//	*EncodedValue_FloatResult
	//	*EncodedValue_BinaryResult
	//	*EncodedValue_StringResult
	//	*EncodedValue_JsonObjectResult
	//	*EncodedValue_NullResult
	//	*EncodedValue_CustomObjectResult
	Value isEncodedValue_Value `protobuf_oneof:"value"`
}

func (x *EncodedValue) Reset() {
	*x = EncodedValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_basicTypes_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncodedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedValue) ProtoMessage() {}

func (x *EncodedValue) ProtoReflect() protoreflect.Message {
	mi := &file_v1_basicTypes_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedValue.ProtoReflect.Descriptor instead.
func (*EncodedValue) Descriptor() ([]byte, []int) {
	return file_v1_basicTypes_proto_rawDescGZIP(), []int{3}
}

func (m *EncodedValue) GetValue() isEncodedValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *EncodedValue) GetIntResult() int32 {
	if x, ok := x.GetValue().(*EncodedValue_IntResult); ok {
		return x.IntResult
	}
	return 0
}

func (x *EncodedValue) GetLongResult() int64 {
	if x, ok := x.GetValue().(*EncodedValue_LongResult); ok {
		return x.LongResult
	}
	return 0
}

func (x *EncodedValue) GetShortResult() int32 {
	if x, ok := x.GetValue().(*EncodedValue_ShortResult); ok {
		return x.ShortResult
	}
	return 0
}

func (x *EncodedValue) GetByteResult() int32 {
	if x, ok := x.GetValue().(*EncodedValue_ByteResult); ok {
		return x.ByteResult
	}
	return 0
}

func (x *EncodedValue) GetBooleanResult() bool {
	if x, ok := x.GetValue().(*EncodedValue_BooleanResult); ok {
		return x.BooleanResult
	}
	return false
}

func (x *EncodedValue) GetDoubleResult() float64 {
	if x, ok := x.GetValue().(*EncodedValue_DoubleResult); ok {
		return x.DoubleResult
	}
	return 0
}

func (x *EncodedValue) GetFloatResult() float32 {
	if x, ok := x.GetValue().(*EncodedValue_FloatResult); ok {
		return x.FloatResult
	}
	return 0
}

func (x *EncodedValue) GetBinaryResult() []byte {
	if x, ok := x.GetValue().(*EncodedValue_BinaryResult); ok {
		return x.BinaryResult
	}
	return nil
}

func (x *EncodedValue) GetStringResult() string {
	if x, ok := x.GetValue().(*EncodedValue_StringResult); ok {
		return x.StringResult
	}
	return ""
}

func (x *EncodedValue) GetJsonObjectResult() string {
	if x, ok := x.GetValue().(*EncodedValue_JsonObjectResult); ok {
		return x.JsonObjectResult
	}
	return ""
}

func (x *EncodedValue) GetNullResult() _struct.NullValue {
	if x, ok := x.GetValue().(*EncodedValue_NullResult); ok {
		return x.NullResult
	}
	return _struct.NullValue_NULL_VALUE
}

func (x *EncodedValue) GetCustomObjectResult() []byte {
	if x, ok := x.GetValue().(*EncodedValue_CustomObjectResult); ok {
		return x.CustomObjectResult
	}
	return nil
}

type isEncodedValue_Value interface {
	isEncodedValue_Value()
}

type EncodedValue_IntResult struct {
	IntResult int32 `protobuf:"varint,1,opt,name=intResult,proto3,oneof"`
}

type EncodedValue_LongResult struct {
	LongResult int64 `protobuf:"varint,2,opt,name=longResult,proto3,oneof"`
}

type EncodedValue_ShortResult struct {
	ShortResult int32 `protobuf:"varint,3,opt,name=shortResult,proto3,oneof"`
}

type EncodedValue_ByteResult struct {
	ByteResult int32 `protobuf:"varint,4,opt,name=byteResult,proto3,oneof"`
}

type EncodedValue_BooleanResult struct {
	BooleanResult bool `protobuf:"varint,5,opt,name=booleanResult,proto3,oneof"`
}

type EncodedValue_DoubleResult struct {
	DoubleResult float64 `protobuf:"fixed64,6,opt,name=doubleResult,proto3,oneof"`
}

type EncodedValue_FloatResult struct {
	FloatResult float32 `protobuf:"fixed32,7,opt,name=floatResult,proto3,oneof"`
}

type EncodedValue_BinaryResult struct {
	BinaryResult []byte `protobuf:"bytes,8,opt,name=binaryResult,proto3,oneof"`
}

type EncodedValue_StringResult struct {
	StringResult string `protobuf:"bytes,9,opt,name=stringResult,proto3,oneof"`
}

type EncodedValue_JsonObjectResult struct {
	JsonObjectResult string `protobuf:"bytes,10,opt,name=jsonObjectResult,proto3,oneof"`
}

type EncodedValue_NullResult struct {
	NullResult _struct.NullValue `protobuf:"varint,11,opt,name=nullResult,proto3,enum=google.protobuf.NullValue,oneof"`
}

type EncodedValue_CustomObjectResult struct {
	// Result serialized using a custom serialization format. This can only be used if
	// A HandshakeRequest is sent with valueFormat set to a valid format.
	//
	// See HandshakeRequest.valueFormat.
	CustomObjectResult []byte `protobuf:"bytes,12,opt,name=customObjectResult,proto3,oneof"`
}

func (*EncodedValue_IntResult) isEncodedValue_Value() {}

func (*EncodedValue_LongResult) isEncodedValue_Value() {}

func (*EncodedValue_ShortResult) isEncodedValue_Value() {}

func (*EncodedValue_ByteResult) isEncodedValue_Value() {}

func (*EncodedValue_BooleanResult) isEncodedValue_Value() {}

func (*EncodedValue_DoubleResult) isEncodedValue_Value() {}

func (*EncodedValue_FloatResult) isEncodedValue_Value() {}

func (*EncodedValue_BinaryResult) isEncodedValue_Value() {}

func (*EncodedValue_StringResult) isEncodedValue_Value() {}

func (*EncodedValue_JsonObjectResult) isEncodedValue_Value() {}

func (*EncodedValue_NullResult) isEncodedValue_Value() {}

func (*EncodedValue_CustomObjectResult) isEncodedValue_Value() {}

type Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port     int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Server) Reset() {
	*x = Server{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_basicTypes_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_v1_basicTypes_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_v1_basicTypes_proto_rawDescGZIP(), []int{4}
}

func (x *Server) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Server) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode ErrorCode `protobuf:"varint,1,opt,name=errorCode,proto3,enum=org.apache.geode.internal.protocol.protobuf.v1.ErrorCode" json:"errorCode,omitempty"`
	Message   string    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_basicTypes_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_v1_basicTypes_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_v1_basicTypes_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_INVALID_ERROR_CODE
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type KeyedError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *EncodedValue `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Error *Error        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *KeyedError) Reset() {
	*x = KeyedError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_basicTypes_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyedError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyedError) ProtoMessage() {}

func (x *KeyedError) ProtoReflect() protoreflect.Message {
	mi := &file_v1_basicTypes_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyedError.ProtoReflect.Descriptor instead.
func (*KeyedError) Descriptor() ([]byte, []int) {
	return file_v1_basicTypes_proto_rawDescGZIP(), []int{6}
}

func (x *KeyedError) GetKey() *EncodedValue {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyedError) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_v1_basicTypes_proto protoreflect.FileDescriptor

var file_v1_basicTypes_proto_rawDesc = []byte{
	0x0a, 0x13, 0x76, 0x31, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x4e, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x6f,
	0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x52, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6f,
	0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x6a, 0x0a, 0x10, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x56, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x79, 0x0a,
	0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x52, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x40, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x67,
	0x65, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x22, 0xfb, 0x03, 0x0a, 0x0c, 0x45, 0x6e, 0x63,
	0x6f, 0x64, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x09, 0x69, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x09,
	0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0a, 0x6c, 0x6f, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52,
	0x0a, 0x6c, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x0b, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x48, 0x00, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x20, 0x0a, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x26, 0x0a, 0x0d, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x0d, 0x62, 0x6f, 0x6f, 0x6c,
	0x65, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x0c, 0x64, 0x6f, 0x75,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x48,
	0x00, 0x52, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x22, 0x0a, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0b, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x0c, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0c, 0x62, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x0c, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x2c, 0x0a, 0x10, 0x6a, 0x73, 0x6f, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x10, 0x6a, 0x73, 0x6f,
	0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3c, 0x0a,
	0x0a, 0x6e, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52,
	0x0a, 0x6e, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x30, 0x0a, 0x12, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x12, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x07, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x38, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x22, 0x7a, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x57, 0x0a, 0x09, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x39, 0x2e, 0x6f,
	0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa9, 0x01, 0x0a,
	0x0a, 0x4b, 0x65, 0x79, 0x65, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x4e, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6f, 0x72, 0x67, 0x2e, 0x61,
	0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x4b, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x6f, 0x72, 0x67,
	0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a, 0x8d, 0x02, 0x0a, 0x09, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x10, 0x00, 0x12, 0x1b,
	0x0a, 0x17, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x52, 0x45, 0x51, 0x55, 0x49, 0x52, 0x45, 0x44, 0x10, 0x0a, 0x12, 0x19, 0x0a, 0x15, 0x41,
	0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x46, 0x41,
	0x49, 0x4c, 0x45, 0x44, 0x10, 0x0b, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44,
	0x59, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x45, 0x44, 0x10,
	0x0c, 0x12, 0x20, 0x0a, 0x1c, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x45,
	0x44, 0x10, 0x0d, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x14, 0x12, 0x13, 0x0a,
	0x0f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54,
	0x10, 0x32, 0x12, 0x19, 0x0a, 0x15, 0x55, 0x4e, 0x53, 0x55, 0x50, 0x50, 0x4f, 0x52, 0x54, 0x45,
	0x44, 0x5f, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x3c, 0x12, 0x10, 0x0a,
	0x0c, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x64, 0x12,
	0x17, 0x0a, 0x13, 0x4e, 0x4f, 0x5f, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x5f,
	0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x67, 0x65, 0x6f, 0x64,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_basicTypes_proto_rawDescOnce sync.Once
	file_v1_basicTypes_proto_rawDescData = file_v1_basicTypes_proto_rawDesc
)

func file_v1_basicTypes_proto_rawDescGZIP() []byte {
	file_v1_basicTypes_proto_rawDescOnce.Do(func() {
		file_v1_basicTypes_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_basicTypes_proto_rawDescData)
	})
	return file_v1_basicTypes_proto_rawDescData
}

var file_v1_basicTypes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_basicTypes_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_basicTypes_proto_goTypes = []interface{}{
	(ErrorCode)(0),           // 0: org.apache.geode.internal.protocol.protobuf.v1.ErrorCode
	(*Entry)(nil),            // 1: org.apache.geode.internal.protocol.protobuf.v1.Entry
	(*EncodedValueList)(nil), // 2: org.apache.geode.internal.protocol.protobuf.v1.EncodedValueList
	(*Table)(nil),            // 3: org.apache.geode.internal.protocol.protobuf.v1.Table
	(*EncodedValue)(nil),     // 4: org.apache.geode.internal.protocol.protobuf.v1.EncodedValue
	(*Server)(nil),           // 5: org.apache.geode.internal.protocol.protobuf.v1.Server
	(*Error)(nil),            // 6: org.apache.geode.internal.protocol.protobuf.v1.Error
	(*KeyedError)(nil),       // 7: org.apache.geode.internal.protocol.protobuf.v1.KeyedError
	(_struct.NullValue)(0),   // 8: google.protobuf.NullValue
}
var file_v1_basicTypes_proto_depIdxs = []int32{
	4, // 0: org.apache.geode.internal.protocol.protobuf.v1.Entry.key:type_name -> org.apache.geode.internal.protocol.protobuf.v1.EncodedValue
	4, // 1: org.apache.geode.internal.protocol.protobuf.v1.Entry.value:type_name -> org.apache.geode.internal.protocol.protobuf.v1.EncodedValue
	4, // 2: org.apache.geode.internal.protocol.protobuf.v1.EncodedValueList.element:type_name -> org.apache.geode.internal.protocol.protobuf.v1.EncodedValue
	2, // 3: org.apache.geode.internal.protocol.protobuf.v1.Table.row:type_name -> org.apache.geode.internal.protocol.protobuf.v1.EncodedValueList
	8, // 4: org.apache.geode.internal.protocol.protobuf.v1.EncodedValue.nullResult:type_name -> google.protobuf.NullValue
	0, // 5: org.apache.geode.internal.protocol.protobuf.v1.Error.errorCode:type_name -> org.apache.geode.internal.protocol.protobuf.v1.ErrorCode
	4, // 6: org.apache.geode.internal.protocol.protobuf.v1.KeyedError.key:type_name -> org.apache.geode.internal.protocol.protobuf.v1.EncodedValue
	6, // 7: org.apache.geode.internal.protocol.protobuf.v1.KeyedError.error:type_name -> org.apache.geode.internal.protocol.protobuf.v1.Error
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_v1_basicTypes_proto_init() }
func file_v1_basicTypes_proto_init() {
	if File_v1_basicTypes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_basicTypes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_basicTypes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodedValueList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_basicTypes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Table); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_basicTypes_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncodedValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_basicTypes_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_basicTypes_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_basicTypes_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyedError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_basicTypes_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*EncodedValue_IntResult)(nil),
		(*EncodedValue_LongResult)(nil),
		(*EncodedValue_ShortResult)(nil),
		(*EncodedValue_ByteResult)(nil),
		(*EncodedValue_BooleanResult)(nil),
		(*EncodedValue_DoubleResult)(nil),
		(*EncodedValue_FloatResult)(nil),
		(*EncodedValue_BinaryResult)(nil),
		(*EncodedValue_StringResult)(nil),
		(*EncodedValue_JsonObjectResult)(nil),
		(*EncodedValue_NullResult)(nil),
		(*EncodedValue_CustomObjectResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_basicTypes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_basicTypes_proto_goTypes,
		DependencyIndexes: file_v1_basicTypes_proto_depIdxs,
		EnumInfos:         file_v1_basicTypes_proto_enumTypes,
		MessageInfos:      file_v1_basicTypes_proto_msgTypes,
	}.Build()
	File_v1_basicTypes_proto = out.File
	file_v1_basicTypes_proto_rawDesc = nil
	file_v1_basicTypes_proto_goTypes = nil
	file_v1_basicTypes_proto_depIdxs = nil
}
