//
// Licensed to the Apache Software Foundation (ASF) under one or more contributor license
// agreements. See the NOTICE file distributed with this work for additional information regarding
// copyright ownership. The ASF licenses this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance with the License. You may obtain a
// copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License
// is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
// or implied. See the License for the specific language governing permissions and limitations under
// the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: protocolVersion.proto

package protobuf

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MajorVersions int32

const (
	MajorVersions_INVALID_MAJOR_VERSION MajorVersions = 0 // Protobuf requires 0 based enum
	MajorVersions_CURRENT_MAJOR_VERSION MajorVersions = 1 // Initial message structure and handshake protocol
)

// Enum value maps for MajorVersions.
var (
	MajorVersions_name = map[int32]string{
		0: "INVALID_MAJOR_VERSION",
		1: "CURRENT_MAJOR_VERSION",
	}
	MajorVersions_value = map[string]int32{
		"INVALID_MAJOR_VERSION": 0,
		"CURRENT_MAJOR_VERSION": 1,
	}
)

func (x MajorVersions) Enum() *MajorVersions {
	p := new(MajorVersions)
	*p = x
	return p
}

func (x MajorVersions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MajorVersions) Descriptor() protoreflect.EnumDescriptor {
	return file_protocolVersion_proto_enumTypes[0].Descriptor()
}

func (MajorVersions) Type() protoreflect.EnumType {
	return &file_protocolVersion_proto_enumTypes[0]
}

func (x MajorVersions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MajorVersions.Descriptor instead.
func (MajorVersions) EnumDescriptor() ([]byte, []int) {
	return file_protocolVersion_proto_rawDescGZIP(), []int{0}
}

type MinorVersions int32

const (
	MinorVersions_INVALID_MINOR_VERSION MinorVersions = 0 // Protobuf requires 0 based enum
	MinorVersions_CURRENT_MINOR_VERSION MinorVersions = 1 // Protobuf implementation at initial release
)

// Enum value maps for MinorVersions.
var (
	MinorVersions_name = map[int32]string{
		0: "INVALID_MINOR_VERSION",
		1: "CURRENT_MINOR_VERSION",
	}
	MinorVersions_value = map[string]int32{
		"INVALID_MINOR_VERSION": 0,
		"CURRENT_MINOR_VERSION": 1,
	}
)

func (x MinorVersions) Enum() *MinorVersions {
	p := new(MinorVersions)
	*p = x
	return p
}

func (x MinorVersions) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MinorVersions) Descriptor() protoreflect.EnumDescriptor {
	return file_protocolVersion_proto_enumTypes[1].Descriptor()
}

func (MinorVersions) Type() protoreflect.EnumType {
	return &file_protocolVersion_proto_enumTypes[1]
}

func (x MinorVersions) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MinorVersions.Descriptor instead.
func (MinorVersions) EnumDescriptor() ([]byte, []int) {
	return file_protocolVersion_proto_rawDescGZIP(), []int{1}
}

type NewConnectionClientVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MajorVersion uint32 `protobuf:"fixed32,1,opt,name=majorVersion,proto3" json:"majorVersion,omitempty"`
	MinorVersion uint32 `protobuf:"fixed32,2,opt,name=minorVersion,proto3" json:"minorVersion,omitempty"`
}

func (x *NewConnectionClientVersion) Reset() {
	*x = NewConnectionClientVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocolVersion_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewConnectionClientVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewConnectionClientVersion) ProtoMessage() {}

func (x *NewConnectionClientVersion) ProtoReflect() protoreflect.Message {
	mi := &file_protocolVersion_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewConnectionClientVersion.ProtoReflect.Descriptor instead.
func (*NewConnectionClientVersion) Descriptor() ([]byte, []int) {
	return file_protocolVersion_proto_rawDescGZIP(), []int{0}
}

func (x *NewConnectionClientVersion) GetMajorVersion() uint32 {
	if x != nil {
		return x.MajorVersion
	}
	return 0
}

func (x *NewConnectionClientVersion) GetMinorVersion() uint32 {
	if x != nil {
		return x.MinorVersion
	}
	return 0
}

type VersionAcknowledgement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerMajorVersion int32 `protobuf:"varint,1,opt,name=serverMajorVersion,proto3" json:"serverMajorVersion,omitempty"`
	ServerMinorVersion int32 `protobuf:"varint,2,opt,name=serverMinorVersion,proto3" json:"serverMinorVersion,omitempty"`
	VersionAccepted    bool  `protobuf:"varint,3,opt,name=versionAccepted,proto3" json:"versionAccepted,omitempty"`
}

func (x *VersionAcknowledgement) Reset() {
	*x = VersionAcknowledgement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocolVersion_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionAcknowledgement) ProtoMessage() {}

func (x *VersionAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_protocolVersion_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionAcknowledgement.ProtoReflect.Descriptor instead.
func (*VersionAcknowledgement) Descriptor() ([]byte, []int) {
	return file_protocolVersion_proto_rawDescGZIP(), []int{1}
}

func (x *VersionAcknowledgement) GetServerMajorVersion() int32 {
	if x != nil {
		return x.ServerMajorVersion
	}
	return 0
}

func (x *VersionAcknowledgement) GetServerMinorVersion() int32 {
	if x != nil {
		return x.ServerMinorVersion
	}
	return 0
}

func (x *VersionAcknowledgement) GetVersionAccepted() bool {
	if x != nil {
		return x.VersionAccepted
	}
	return false
}

var File_protocolVersion_proto protoreflect.FileDescriptor

var file_protocolVersion_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2b, 0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x22, 0x64, 0x0a, 0x1a, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0c, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x07, 0x52, 0x0c, 0x6d, 0x69,
	0x6e, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xa2, 0x01, 0x0a, 0x16, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x61, 0x6a, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x69, 0x6e, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x12, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x69, 0x6e, 0x6f, 0x72, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x65, 0x64, 0x2a,
	0x45, 0x0a, 0x0d, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x19, 0x0a, 0x15, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x4d, 0x41, 0x4a, 0x4f,
	0x52, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x43,
	0x55, 0x52, 0x52, 0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x41, 0x4a, 0x4f, 0x52, 0x5f, 0x56, 0x45, 0x52,
	0x53, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x2a, 0x45, 0x0a, 0x0d, 0x4d, 0x69, 0x6e, 0x6f, 0x72, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x19, 0x0a, 0x15, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x5f, 0x4d, 0x49, 0x4e, 0x4f, 0x52, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e,
	0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x54, 0x5f, 0x4d, 0x49,
	0x4e, 0x4f, 0x52, 0x5f, 0x56, 0x45, 0x52, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x42, 0x10, 0x5a,
	0x0e, 0x67, 0x65, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocolVersion_proto_rawDescOnce sync.Once
	file_protocolVersion_proto_rawDescData = file_protocolVersion_proto_rawDesc
)

func file_protocolVersion_proto_rawDescGZIP() []byte {
	file_protocolVersion_proto_rawDescOnce.Do(func() {
		file_protocolVersion_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocolVersion_proto_rawDescData)
	})
	return file_protocolVersion_proto_rawDescData
}

var file_protocolVersion_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protocolVersion_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocolVersion_proto_goTypes = []interface{}{
	(MajorVersions)(0),                 // 0: org.apache.geode.internal.protocol.protobuf.MajorVersions
	(MinorVersions)(0),                 // 1: org.apache.geode.internal.protocol.protobuf.MinorVersions
	(*NewConnectionClientVersion)(nil), // 2: org.apache.geode.internal.protocol.protobuf.NewConnectionClientVersion
	(*VersionAcknowledgement)(nil),     // 3: org.apache.geode.internal.protocol.protobuf.VersionAcknowledgement
}
var file_protocolVersion_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocolVersion_proto_init() }
func file_protocolVersion_proto_init() {
	if File_protocolVersion_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocolVersion_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewConnectionClientVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocolVersion_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionAcknowledgement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocolVersion_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocolVersion_proto_goTypes,
		DependencyIndexes: file_protocolVersion_proto_depIdxs,
		EnumInfos:         file_protocolVersion_proto_enumTypes,
		MessageInfos:      file_protocolVersion_proto_msgTypes,
	}.Build()
	File_protocolVersion_proto = out.File
	file_protocolVersion_proto_rawDesc = nil
	file_protocolVersion_proto_goTypes = nil
	file_protocolVersion_proto_depIdxs = nil
}
